export interface CategoryQuestion {
  question_order: number;
  question_text: string;
  question_type: 'multiple_choice' | 'text' | 'number';
  options?: string[];
  required: boolean;
  output_key: string;
}

export interface CategoryConfig {
  category: string;
  category_description: string;
  trade?: string;
  questions: CategoryQuestion[];
}

export const categoryConfig: CategoryConfig[] = [
  {
    category: 'Boilers',
    category_description: 'Central heating systems, boiler installation, etc.',
    trade: 'Plumbing',
    questions: [
      {
        question_order: 1,
        question_text: 'What type of boiler do you have?',
        question_type: 'multiple_choice',
        options: ['Gas', 'Oil', 'Electric', 'Other/Not sure'],
        required: true,
        output_key: 'boilers_q1',
      },
      {
        question_order: 2,
        question_text: 'What needs doing to the boiler?',
        question_type: 'multiple_choice',
        options: ['Repair', 'Service', 'Installation', 'Removal', 'Gas safety certificate'],
        required: true,
        output_key: 'boilers_q2',
      },
      {
        question_order: 3,
        question_text: 'Is the property domestic or commercial?',
        question_type: 'multiple_choice',
        options: ['Domestic', 'Commercial'],
        required: true,
        output_key: 'boilers_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Radiators',
    category_description: 'Radiators installation, repairs, etc.',
    trade: 'Plumbing',
    questions: [
      {
        question_order: 1,
        question_text: 'What do you need help with?',
        question_type: 'multiple_choice',
        options: ['Install new radiator', 'Move existing radiator', 'Repair leak', 'Cold radiator issue'],
        required: true,
        output_key: 'radiators_q1',
      },
      {
        question_order: 2,
        question_text: 'How many radiators are involved (approx)?',
        question_type: 'multiple_choice',
        options: ['1-2', '3-5', '6+'],
        required: true,
        output_key: 'radiators_q2',
      },
      {
        question_order: 3,
        question_text: 'Is this for a domestic or commercial property?',
        question_type: 'multiple_choice',
        options: ['Domestic', 'Commercial'],
        required: true,
        output_key: 'radiators_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Appliances',
    category_description: 'Dishwasher, washing machine, etc.',
    trade: 'Plumbing',
    questions: [
      {
        question_order: 1,
        question_text: 'Which appliance do you need help with?',
        question_type: 'multiple_choice',
        options: ['Dishwasher', 'Washing machine', 'Fridge/Freezer', 'Other'],
        required: true,
        output_key: 'appliances_q1',
      },
      {
        question_order: 2,
        question_text: 'What needs doing?',
        question_type: 'multiple_choice',
        options: ['Installation', 'Replacement', 'Repair', 'Removal'],
        required: true,
        output_key: 'appliances_q2',
      },
      {
        question_order: 3,
        question_text: 'Is the property domestic or commercial?',
        question_type: 'multiple_choice',
        options: ['Domestic', 'Commercial'],
        required: true,
        output_key: 'appliances_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Fixtures',
    category_description: 'Shower, toilet, sink, etc.',
    trade: 'Plumbing',
    questions: [
      {
        question_order: 1,
        question_text: 'Which fixture needs attention?',
        question_type: 'multiple_choice',
        options: ['Shower', 'Toilet', 'Sink', 'Bath', 'Other'],
        required: true,
        output_key: 'fixtures_q1',
      },
      {
        question_order: 2,
        question_text: 'What is the issue?',
        question_type: 'multiple_choice',
        options: ['Install new', 'Repair', 'Blocked', 'Leaking'],
        required: true,
        output_key: 'fixtures_q2',
      },
      {
        question_order: 3,
        question_text: 'Is the property domestic or commercial?',
        question_type: 'multiple_choice',
        options: ['Domestic', 'Commercial'],
        required: true,
        output_key: 'fixtures_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Pipework, taps & drainage',
    category_description: 'Pipe alterations, blockages, leaks, macerator, etc.',
    trade: 'Plumbing',
    questions: [
      {
        question_order: 1,
        question_text: 'What best describes the job?',
        question_type: 'multiple_choice',
        options: ['Leak repair', 'Pipe alteration', 'Blocked pipe', 'Replace tap', 'Install new tap'],
        required: true,
        output_key: 'pipework,_taps_and_drainage_q1',
      },
      {
        question_order: 2,
        question_text: 'Is this an urgent issue?',
        question_type: 'multiple_choice',
        options: ['Yes', 'No', 'Unsure'],
        required: true,
        output_key: 'pipework,_taps_and_drainage_q2',
      },
      {
        question_order: 3,
        question_text: 'Is the property domestic or commercial?',
        question_type: 'multiple_choice',
        options: ['Domestic', 'Commercial'],
        required: true,
        output_key: 'pipework,_taps_and_drainage_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Boilers (gas)',
    category_description: 'Gas boiler installation, repair, service, etc.',
    trade: 'Gas Engineer',
    questions: [
      {
        question_order: 1,
        question_text: 'What fuel does your boiler use?',
        question_type: 'multiple_choice',
        options: ['Natural gas', 'LPG', 'Not sure'],
        required: true,
        output_key: 'boilers_gas_q1',
      },
      {
        question_order: 2,
        question_text: 'What needs doing?',
        question_type: 'multiple_choice',
        options: ['Installation / Replacement', 'Repair', 'Service', 'Removal / Relocation', 'Gas safety check'],
        required: true,
        output_key: 'boilers_gas_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'boilers_gas_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Gas hobs, cookers & ovens',
    category_description: 'Gas hob, cooker, oven installation, repair, etc.',
    trade: 'Gas Engineer',
    questions: [
      {
        question_order: 1,
        question_text: 'Which appliance?',
        question_type: 'multiple_choice',
        options: ['Gas hob', 'Gas cooker (freestanding)', 'Gas oven', 'Gas range cooker'],
        required: true,
        output_key: 'gas_hobs_cookers_and_ovens_q1',
      },
      {
        question_order: 2,
        question_text: 'What needs doing?',
        question_type: 'multiple_choice',
        options: ['Install new', 'Replace existing', 'Repair', 'Disconnect / remove'],
        required: true,
        output_key: 'gas_hobs_cookers_and_ovens_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'gas_hobs_cookers_and_ovens_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Gas fires & flues',
    category_description: 'Gas fire, stove, flue lining, back boiler, etc.',
    trade: 'Gas Engineer',
    questions: [
      {
        question_order: 1,
        question_text: 'What type of unit?',
        question_type: 'multiple_choice',
        options: ['Gas fire (decorative)', 'Gas stove', 'Flue / chimney lining', 'Back boiler'],
        required: true,
        output_key: 'gas_fires_and_flues_q1',
      },
      {
        question_order: 2,
        question_text: 'What needs doing?',
        question_type: 'multiple_choice',
        options: ['Install new', 'Service', 'Repair', 'Removal'],
        required: true,
        output_key: 'gas_fires_and_flues_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'gas_fires_and_flues_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Gas safety certificates (CP12)',
    category_description: 'Landlord / homeowner gas safety certificates.',
    trade: 'Gas Engineer',
    questions: [
      {
        question_order: 1,
        question_text: 'Which certificate?',
        question_type: 'multiple_choice',
        options: ['Landlord gas safety (CP12)', 'Homeowner gas safety check', 'New tenancy certificate', 'Sale of property certificate'],
        required: true,
        output_key: 'gas_safety_certificates_cp12_q1',
      },
      {
        question_order: 2,
        question_text: 'How many gas appliances to test?',
        question_type: 'multiple_choice',
        options: ['1', '2–3', '4+'],
        required: true,
        output_key: 'gas_safety_certificates_cp12_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'gas_safety_certificates_cp12_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Gas leaks & emergency',
    category_description: 'Smell of gas, suspected leak, CO alarm, emergency call-out.',
    trade: 'Gas Engineer',
    questions: [
      {
        question_order: 1,
        question_text: 'What is the issue?',
        question_type: 'multiple_choice',
        options: ['Smell of gas', 'Suspected leak', 'Carbon monoxide alarm triggered', 'Boiler has shut down'],
        required: true,
        output_key: 'gas_leaks_and_emergency_q1',
      },
      {
        question_order: 2,
        question_text: 'How urgent?',
        question_type: 'multiple_choice',
        options: ['Now (emergency)', 'Within 24 hours', 'Within a few days'],
        required: true,
        output_key: 'gas_leaks_and_emergency_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'gas_leaks_and_emergency_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Gas pipework',
    category_description: 'New pipe runs, alterations, capping, meter relocation.',
    trade: 'Gas Engineer',
    questions: [
      {
        question_order: 1,
        question_text: 'What best describes the job?',
        question_type: 'multiple_choice',
        options: ['New gas pipe run', 'Pipe alteration / extension', 'Pipe capping', 'Meter relocation'],
        required: true,
        output_key: 'gas_pipework_q1',
      },
      {
        question_order: 2,
        question_text: 'Approximate length / scale?',
        question_type: 'multiple_choice',
        options: ['Short (under 2m)', 'Medium (2–5m)', 'Long (5m+) / Major'],
        required: true,
        output_key: 'gas_pipework_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'gas_pipework_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },

  // ── Roofing ─────────────────────────────────────────────────────────────
  {
    category: 'Pitched roof repairs',
    category_description: 'Slipped/missing tiles, cracked tiles, leaks, sagging and storm damage on pitched roofs.',
    trade: 'Roofing',
    questions: [
      {
        question_order: 1,
        question_text: "What's the issue?",
        question_type: 'multiple_choice',
        options: ['Slipped / missing tiles', 'Cracked or damaged tiles', 'Leak (cause unknown)', 'Sagging roof', 'Storm damage'],
        required: true,
        output_key: 'pitched_roof_repairs_q1',
      },
      {
        question_order: 2,
        question_text: 'How big is the affected area?',
        question_type: 'multiple_choice',
        options: ['1-3 tiles', '4-10 tiles', '10+ tiles / large area'],
        required: true,
        output_key: 'pitched_roof_repairs_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'pitched_roof_repairs_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Full or partial reroof',
    category_description: 'Full reroofs, partial reroofs, refelting and large-scale tile replacement.',
    trade: 'Roofing',
    questions: [
      {
        question_order: 1,
        question_text: "What's the scope?",
        question_type: 'multiple_choice',
        options: ['Full reroof', 'Partial reroof (one side)', 'Re-felt and batten only', 'Large-scale tile replacement'],
        required: true,
        output_key: 'full_or_partial_reroof_q1',
      },
      {
        question_order: 2,
        question_text: 'Roof covering material?',
        question_type: 'multiple_choice',
        options: ['Concrete tiles', 'Clay tiles', 'Slate', 'Other / Not sure'],
        required: true,
        output_key: 'full_or_partial_reroof_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'full_or_partial_reroof_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Flat roof',
    category_description: 'Install, replace or repair flat roofs (felt, EPDM, GRP).',
    trade: 'Roofing',
    questions: [
      {
        question_order: 1,
        question_text: 'What needs doing?',
        question_type: 'multiple_choice',
        options: ['Install new flat roof', 'Replace existing flat roof', 'Repair leak', 'Annual inspection'],
        required: true,
        output_key: 'flat_roof_q1',
      },
      {
        question_order: 2,
        question_text: 'Flat roof material?',
        question_type: 'multiple_choice',
        options: ['Felt', 'EPDM rubber', 'GRP fibreglass', 'Not sure'],
        required: true,
        output_key: 'flat_roof_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'flat_roof_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Gutters, fascias & soffits',
    category_description: 'Repair, replace or clean gutters, fascias and soffits.',
    trade: 'Roofing',
    questions: [
      {
        question_order: 1,
        question_text: "What's the job?",
        question_type: 'multiple_choice',
        options: ['Gutter cleaning', 'Gutter repair', 'Gutter section replacement', 'Full gutter replacement', 'Fascia / soffit replacement'],
        required: true,
        output_key: 'gutters_fascias_and_soffits_q1',
      },
      {
        question_order: 2,
        question_text: 'Approximate scale?',
        question_type: 'multiple_choice',
        options: ['1 side of property', '2 sides', 'Full perimeter'],
        required: true,
        output_key: 'gutters_fascias_and_soffits_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'gutters_fascias_and_soffits_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Chimney work',
    category_description: 'Repointing, capping, removal, flashing and rebuilds.',
    trade: 'Roofing',
    questions: [
      {
        question_order: 1,
        question_text: "What's needed?",
        question_type: 'multiple_choice',
        options: ['Repointing', 'Chimney capping', 'Lead flashing repair / replace', 'Chimney removal', 'Chimney rebuild'],
        required: true,
        output_key: 'chimney_work_q1',
      },
      {
        question_order: 2,
        question_text: 'How will the chimney be accessed?',
        question_type: 'multiple_choice',
        options: ['Scaffold required', 'Ladder / roof ladder', 'Not sure'],
        required: true,
        output_key: 'chimney_work_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'chimney_work_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Roof windows / skylights',
    category_description: 'Install, replace and repair Velux-style roof windows and skylights.',
    trade: 'Roofing',
    questions: [
      {
        question_order: 1,
        question_text: 'What do you need?',
        question_type: 'multiple_choice',
        options: ['Install new roof window/skylight', 'Replace existing', 'Repair leak / seal', 'Add blind or accessory'],
        required: true,
        output_key: 'roof_windows___skylights_q1',
      },
      {
        question_order: 2,
        question_text: 'How many windows?',
        question_type: 'multiple_choice',
        options: ['1', '2-3', '4+'],
        required: true,
        output_key: 'roof_windows___skylights_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'roof_windows___skylights_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Lead work & flashing',
    category_description: 'Repair or replace lead flashing around chimneys, skylights and valleys.',
    trade: 'Roofing',
    questions: [
      {
        question_order: 1,
        question_text: "What's the job?",
        question_type: 'multiple_choice',
        options: ['Repair existing lead', 'Replace lead flashing', 'New lead install'],
        required: true,
        output_key: 'lead_work_and_flashing_q1',
      },
      {
        question_order: 2,
        question_text: 'Where is the lead work?',
        question_type: 'multiple_choice',
        options: ['Around chimney', 'Around skylight', 'Roof valley', 'Other'],
        required: true,
        output_key: 'lead_work_and_flashing_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'lead_work_and_flashing_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Moss removal & roof cleaning',
    category_description: 'Moss removal, soft-wash cleaning and biocide treatments.',
    trade: 'Roofing',
    questions: [
      {
        question_order: 1,
        question_text: "What's the job?",
        question_type: 'multiple_choice',
        options: ['Moss removal', 'Soft wash clean', 'Apply biocide treatment', 'Roof + gutter clean combo'],
        required: true,
        output_key: 'moss_removal_and_roof_cleaning_q1',
      },
      {
        question_order: 2,
        question_text: 'Scale of clean?',
        question_type: 'multiple_choice',
        options: ['Single side', 'Whole roof', 'Roof + gutters / full property'],
        required: true,
        output_key: 'moss_removal_and_roof_cleaning_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'moss_removal_and_roof_cleaning_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Fuse board (Consumer unit)',
    category_description: 'Consumer unit replacement, upgrades, RCD/RCBO, circuit additions, inspection.',
    trade: 'Electrical',
    questions: [
      {
        question_order: 1,
        question_text: 'What needs doing?',
        question_type: 'multiple_choice',
        options: ['Replace consumer unit', 'Upgrade to RCD/RCBO', 'Add circuit breaker', 'Repair/Fault', 'Inspection'],
        required: true,
        output_key: 'fuse_board_(consumer_unit)_q1',
      },
      {
        question_order: 2,
        question_text: 'How old is the existing unit?',
        question_type: 'multiple_choice',
        options: ['Less than 10 years', '10–25 years', 'More than 25 years', 'Not sure'],
        required: true,
        output_key: 'fuse_board_(consumer_unit)_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'fuse_board_(consumer_unit)_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Lighting',
    category_description: 'Internal/external lighting, downlights, smart lighting install or repair.',
    trade: 'Electrical',
    questions: [
      {
        question_order: 1,
        question_text: 'What do you need help with?',
        question_type: 'multiple_choice',
        options: ['Install new light(s)', 'Replace existing light(s)', 'Repair faulty light', 'Install downlights/spotlights', 'Install outdoor lighting', 'Install smart lighting'],
        required: true,
        output_key: 'lighting_q1',
      },
      {
        question_order: 2,
        question_text: 'How many lights/fittings are involved?',
        question_type: 'multiple_choice',
        options: ['1', '2–5', '6+'],
        required: true,
        output_key: 'lighting_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'lighting_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Sockets & switches',
    category_description: 'Install, move, replace or repair sockets, switches and USB outlets.',
    trade: 'Electrical',
    questions: [
      {
        question_order: 1,
        question_text: 'What do you need help with?',
        question_type: 'multiple_choice',
        options: ['Install new socket', 'Move existing socket', 'Replace socket/switch', 'Install USB socket', 'Repair faulty socket/switch'],
        required: true,
        output_key: 'sockets_and_switches_q1',
      },
      {
        question_order: 2,
        question_text: 'How many sockets/switches?',
        question_type: 'multiple_choice',
        options: ['1', '2–5', '6+'],
        required: true,
        output_key: 'sockets_and_switches_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'sockets_and_switches_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Rewiring & cabling',
    category_description: 'Full or partial rewires, cable runs and electrical fault finding.',
    trade: 'Electrical',
    questions: [
      {
        question_order: 1,
        question_text: 'What best describes the job?',
        question_type: 'multiple_choice',
        options: ['Full rewire', 'Partial rewire (room or zone)', 'Cable run (e.g. for new appliance)', 'Fault finding/diagnostics'],
        required: true,
        output_key: 'rewiring_and_cabling_q1',
      },
      {
        question_order: 2,
        question_text: 'Is the power currently working?',
        question_type: 'multiple_choice',
        options: ['Power working', 'Partial power loss', 'No power / unsafe', 'Not sure'],
        required: true,
        output_key: 'rewiring_and_cabling_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'rewiring_and_cabling_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'EV chargers',
    category_description: 'Home electric vehicle charger install, replace, repair or relocate.',
    trade: 'Electrical',
    questions: [
      {
        question_order: 1,
        question_text: 'What do you need?',
        question_type: 'multiple_choice',
        options: ['Install new EV charger', 'Replace/upgrade existing', 'Repair fault', 'Move existing'],
        required: true,
        output_key: 'ev_chargers_q1',
      },
      {
        question_order: 2,
        question_text: 'Where is it being installed?',
        question_type: 'multiple_choice',
        options: ['Attached garage', 'Driveway (wall-mounted)', 'Driveway (post-mounted)', 'Carport', 'Other'],
        required: true,
        output_key: 'ev_chargers_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'ev_chargers_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Testing & certificates',
    category_description: 'EICR, landlord certs, PAT testing and visual inspections.',
    trade: 'Electrical',
    questions: [
      {
        question_order: 1,
        question_text: 'Which certificate/test?',
        question_type: 'multiple_choice',
        options: ['EICR (full property)', 'Landlord cert', 'PAT testing (appliances)', 'Visual inspection only'],
        required: true,
        output_key: 'testing_and_certificates_q1',
      },
      {
        question_order: 2,
        question_text: 'Approximate property size?',
        question_type: 'multiple_choice',
        options: ['1 bed', '2–3 bed', '4+ bed'],
        required: true,
        output_key: 'testing_and_certificates_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'testing_and_certificates_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Appliances & hardwired equipment',
    category_description: 'Electric cookers, showers, hobs, extractor fans and other hardwired kit.',
    trade: 'Electrical',
    questions: [
      {
        question_order: 1,
        question_text: 'Which appliance?',
        question_type: 'multiple_choice',
        options: ['Electric oven/cooker', 'Electric shower', 'Electric hob', 'Extractor fan', 'Other hardwired appliance'],
        required: true,
        output_key: 'appliances_and_hardwired_equipment_q1',
      },
      {
        question_order: 2,
        question_text: 'What needs doing?',
        question_type: 'multiple_choice',
        options: ['Install new', 'Replace existing', 'Repair', 'Disconnect/remove'],
        required: true,
        output_key: 'appliances_and_hardwired_equipment_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'appliances_and_hardwired_equipment_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  {
    category: 'Smart home & networking',
    category_description: 'Smart thermostats, doorbells, alarms, CCTV and data cabling.',
    trade: 'Electrical',
    questions: [
      {
        question_order: 1,
        question_text: 'What do you need help with?',
        question_type: 'multiple_choice',
        options: ['Wi-Fi access point / mesh', 'Smart thermostat wiring', 'Video doorbell', 'Burglar alarm', 'CCTV install', 'Network/data cabling'],
        required: true,
        output_key: 'smart_home_and_networking_q1',
      },
      {
        question_order: 2,
        question_text: 'How many devices/points?',
        question_type: 'multiple_choice',
        options: ['1', '2–5', '6+'],
        required: true,
        output_key: 'smart_home_and_networking_q2',
      },
      {
        question_order: 3,
        question_text: 'Property type',
        question_type: 'multiple_choice',
        options: ['House', 'Flat', 'Bungalow', 'Other'],
        required: true,
        output_key: 'smart_home_and_networking_q3',
      },
      {
        question_order: 4,
        question_text: 'Add a short description of the job (include any useful details).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  // ─── Builder ───────────────────────────────────────────────────────────────
  {
    category: 'General Building',
    category_description: 'Extensions, conversions, structural work, brickwork.',
    trade: 'Builder',
    questions: [
      {
        question_order: 1,
        question_text: 'What type of building work is needed?',
        question_type: 'multiple_choice',
        options: ['Extension', 'Loft conversion', 'Structural repair', 'Brickwork / pointing', 'Garage conversion', 'Other'],
        required: true,
        output_key: 'builder_q1',
      },
      {
        question_order: 2,
        question_text: 'Approximate scale of the work?',
        question_type: 'multiple_choice',
        options: ['Small (under £5k)', 'Medium (£5k–£20k)', 'Large (over £20k)', 'Not sure'],
        required: true,
        output_key: 'builder_q2',
      },
      {
        question_order: 3,
        question_text: 'Add a short description of the job.',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  // ─── Decorator / Painter ───────────────────────────────────────────────────
  {
    category: 'Interior Decorating',
    category_description: 'Interior and exterior painting, wallpapering.',
    trade: 'Decorator / Painter',
    questions: [
      {
        question_order: 1,
        question_text: 'What needs decorating?',
        question_type: 'multiple_choice',
        options: ['Interior walls & ceilings', 'Woodwork / skirting / doors', 'Exterior painting', 'Wallpapering', 'Full room(s)', 'Whole property'],
        required: true,
        output_key: 'decorator_q1',
      },
      {
        question_order: 2,
        question_text: 'How many rooms / how much area?',
        question_type: 'multiple_choice',
        options: ['1 room', '2–3 rooms', '4+ rooms', 'Whole house'],
        required: true,
        output_key: 'decorator_q2',
      },
      {
        question_order: 3,
        question_text: 'Add a short description (colours, finish, any prep needed).',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  // ─── Carpenter / Joiner ────────────────────────────────────────────────────
  {
    category: 'Carpentry & Joinery',
    category_description: 'Doors, floors, fitted furniture, staircases.',
    trade: 'Carpenter / Joiner',
    questions: [
      {
        question_order: 1,
        question_text: 'What carpentry work is needed?',
        question_type: 'multiple_choice',
        options: ['Door fitting / repair', 'Floor fitting / repair', 'Fitted wardrobe / storage', 'Staircase repair', 'Window frames', 'Decking / garden'],
        required: true,
        output_key: 'carpenter_q1',
      },
      {
        question_order: 2,
        question_text: 'Are materials being supplied by you or the tradesperson?',
        question_type: 'multiple_choice',
        options: ['Trade to supply', 'I will supply', 'Not sure yet'],
        required: false,
        output_key: 'carpenter_q2',
      },
      {
        question_order: 3,
        question_text: 'Add a short description of the job.',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  // ─── Kitchen Installer ─────────────────────────────────────────────────────
  {
    category: 'Kitchen Installation',
    category_description: 'New kitchens, refits, worktops, appliances.',
    trade: 'Kitchen Installer',
    questions: [
      {
        question_order: 1,
        question_text: 'What kitchen work is required?',
        question_type: 'multiple_choice',
        options: ['Full new kitchen', 'Replace doors / worktops only', 'Refit existing units', 'Appliance installation', 'Splashback / tiling'],
        required: true,
        output_key: 'kitchen_q1',
      },
      {
        question_order: 2,
        question_text: 'Is the kitchen already purchased?',
        question_type: 'multiple_choice',
        options: ['Yes — supply and fit', 'No — fit only', 'Not yet decided'],
        required: true,
        output_key: 'kitchen_q2',
      },
      {
        question_order: 3,
        question_text: 'Add a short description.',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  // ─── Bathroom Fitter ───────────────────────────────────────────────────────
  {
    category: 'Bathroom Fitting',
    category_description: 'New bathrooms, showers, tiling, wetrooms.',
    trade: 'Bathroom Fitter',
    questions: [
      {
        question_order: 1,
        question_text: 'What bathroom work is needed?',
        question_type: 'multiple_choice',
        options: ['Full bathroom refit', 'Shower installation', 'Bath replacement', 'Tiling only', 'Wetroom conversion', 'En-suite addition'],
        required: true,
        output_key: 'bathroom_q1',
      },
      {
        question_order: 2,
        question_text: 'Is the bathroom suite already purchased?',
        question_type: 'multiple_choice',
        options: ['Yes — supply and fit', 'No — fit only', 'Not yet decided'],
        required: true,
        output_key: 'bathroom_q2',
      },
      {
        question_order: 3,
        question_text: 'Add a short description.',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  // ─── Plasterer ─────────────────────────────────────────────────────────────
  {
    category: 'Plastering',
    category_description: 'Skimming, rendering, coving, dry lining.',
    trade: 'Plasterer',
    questions: [
      {
        question_order: 1,
        question_text: 'What plastering work is required?',
        question_type: 'multiple_choice',
        options: ['Skim coat (walls/ceilings)', 'Full re-plaster', 'Patch repair', 'External render', 'Coving / cornices', 'Dry lining / stud walls'],
        required: true,
        output_key: 'plasterer_q1',
      },
      {
        question_order: 2,
        question_text: 'How many rooms / how much area?',
        question_type: 'multiple_choice',
        options: ['1 room', '2–3 rooms', '4+ rooms', 'Whole house'],
        required: true,
        output_key: 'plasterer_q2',
      },
      {
        question_order: 3,
        question_text: 'Add a short description.',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  // ─── Locksmith ─────────────────────────────────────────────────────────────
  {
    category: 'Locksmith Services',
    category_description: 'Lock changes, break-ins, security upgrades.',
    trade: 'Locksmith',
    questions: [
      {
        question_order: 1,
        question_text: 'What locksmith service do you need?',
        question_type: 'multiple_choice',
        options: ['Locked out / emergency', 'Lock change / upgrade', 'Break-in repair', 'Key cutting / spare key', 'Multi-point lock repair'],
        required: true,
        output_key: 'locksmith_q1',
      },
      {
        question_order: 2,
        question_text: 'Is this urgent?',
        question_type: 'multiple_choice',
        options: ['Emergency — now', 'Today', 'This week', 'Flexible'],
        required: true,
        output_key: 'locksmith_q2',
      },
      {
        question_order: 3,
        question_text: 'Add a short description.',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
  // ─── Groundworks / Drainage ────────────────────────────────────────────────
  {
    category: 'Groundworks & Drainage',
    category_description: 'Drains, driveways, patios, foundations.',
    trade: 'Groundworks / Drainage',
    questions: [
      {
        question_order: 1,
        question_text: 'What groundwork is needed?',
        question_type: 'multiple_choice',
        options: ['Drain clearance / repair', 'New drainage installation', 'Driveway / paving', 'Patio / decking', 'Foundations / underpinning', 'Soakaway / SUDS'],
        required: true,
        output_key: 'groundworker_q1',
      },
      {
        question_order: 2,
        question_text: 'Is there a specific problem or is this planned work?',
        question_type: 'multiple_choice',
        options: ['Urgent problem', 'Planned improvement', 'Not sure'],
        required: false,
        output_key: 'groundworker_q2',
      },
      {
        question_order: 3,
        question_text: 'Add a short description.',
        question_type: 'text',
        required: false,
        output_key: 'description',
      },
    ],
  },
];
